[package]
name = "dvui"
version = "0.1.0"
edition = "2021"

[lib]
name = "dvui"
path = "src/lib.rs"

[dependencies]
derive_more = {version="2.0.1", features=["full"]}
sdl2 = "0.37.0"
smart-default = "0.7.1"
